from pathlib import Path
import pandas as pd
import matplotlib.pyplot as plt
import json


def generate_report_visuals(report_path: str, out_base: Path) -> list:
    """Generate PNG visualizations for a report file and return list of output file paths.

    report_path: path to .xlsx or .csv report generated by the app
    out_base: base directory (typically REPORTS_DIR) where visuals folder will be created
    """
    p = Path(report_path)
    if not p.exists():
        raise FileNotFoundError(report_path)

    # load dataframe
    if p.suffix.lower() in (".xls", ".xlsx"):
        df = pd.read_excel(p)
    else:
        df = pd.read_csv(p)

    # ensure status column
    if "status" not in df.columns:
        raise ValueError("report missing 'status' column")

    out_dir = out_base / f"{p.stem}_visuals"
    out_dir.mkdir(parents=True, exist_ok=True)

    images = []

    # Pie chart of statuses
    status_counts = df['status'].value_counts()
    fig, ax = plt.subplots(figsize=(6,6), facecolor="#0b0f14")
    colors = {
        'MATCHED':'#064e3b',
        'MISMATCH':'#7f1d1d',
        'MISSING':'#1e293b',
        'POSSIBLE_MATCH':'#065f46'
    }
    wedges, texts, autotexts = ax.pie(
        [status_counts.get(k,0) for k in status_counts.index],
        labels=status_counts.index,
        autopct='%1.1f%%',
        textprops={'color':'#e6eef8'} ,
        colors=[colors.get(k, '#3b4750') for k in status_counts.index]
    )
    ax.set_title('Status distribution', color='#e6eef8')
    ax.set_facecolor('#0b0f14')
    fig.patch.set_facecolor('#0b0f14')
    out_path = out_dir / "status_pie.png"
    fig.savefig(out_path, bbox_inches='tight', dpi=120)
    plt.close(fig)
    images.append(out_path)

    # Bar chart counts
    fig, ax = plt.subplots(figsize=(8,4), facecolor="#0b0f14")
    keys = list(status_counts.index)
    vals = [int(status_counts.get(k,0)) for k in keys]
    bars = ax.bar(keys, vals, color=[colors.get(k, '#3b4750') for k in keys])
    ax.set_xlabel('Status', color='#9aa4b2')
    ax.set_ylabel('Count', color='#9aa4b2')
    ax.set_facecolor('#0b0f14')
    fig.patch.set_facecolor('#0b0f14')
    for spine in ax.spines.values():
        spine.set_color('#081018')
    ax.tick_params(colors='#9aa4b2')
    out_path2 = out_dir / "status_bar.png"
    fig.savefig(out_path2, bbox_inches='tight', dpi=120)
    plt.close(fig)
    images.append(out_path2)

    # Small diagnostics: top mismatches by difference length (if differences column exists)
    if 'differences' in df.columns:
        try:
            difflen = df['differences'].fillna('').apply(lambda x: len(str(x)))
            top = difflen.sort_values(ascending=False).head(10)
            fig, ax = plt.subplots(figsize=(8,4), facecolor="#0b0f14")
            ax.barh(range(len(top)), top.values, color='#0ea5a4')
            ax.set_yticks(range(len(top)))
            ax.set_yticklabels(df.loc[top.index, 'field_key'].fillna('-'))
            ax.invert_yaxis()
            ax.set_xlabel('Difference length', color='#9aa4b2')
            ax.tick_params(colors='#9aa4b2')
            out_path3 = out_dir / "top_diffs.png"
            fig.savefig(out_path3, bbox_inches='tight', dpi=120)
            plt.close(fig)
            images.append(out_path3)
        except Exception:
            pass

    return [str(x) for x in images]
